version: '3.8'

services:
  frontend:
    image: frontend
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - user-facing
      - back-office
    ports:
      - "7887:80"

  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - back-office
      
  backend:
    image: backend
    restart: on-failure
    build:
      dockerfile: ./backend/Dockerfile
    environment:
      - DATABASE_URL=mariadb://admin:password@database:3306/randomizer
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - back-office
  
networks:
  back-office:
  user-facing:
