version: '3.7'

services:
  # frontend:
  #   image: frontend
  #   restart: on-failure
  #   build:
  #     dockerfile: ./frontend/Dockerfile
  #   networks:
  #     - user-facing
  #     - back-office
  #   ports:
  #     - "7887:80"

  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - back-office
      
  backend:
    image: backend
    restart: on-failure
    build:
      dockerfile: ./backend/Dockerfile
    environment:
      - DATABASE_URL=mariadb://admin:password@database:3306/randomizer
      - REDIS_HOST=redis
    depends_on:
      - database
      # - redis
    ports:
      - "80:80"
    networks:
      - back-office

  # redis:
  #   image: redis
  #   restart: always
  #   command: redis-server --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  #   networks:
  #     - back-office
  
networks:
  back-office:
  user-facing:
